# Generated by Django 4.2.7 on 2025-04-21 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username_alter_user_car_smart_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_code',
        ),
        migrations.CreateModel(
            name='NationalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('user', 'code')},
            },
        ),
    ]
