# Generated by Django 4.2.7 on 2025-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='remaining_cars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
