# Generated by Django 4.2.7 on 2025-04-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_alter_load_remaining_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
