# Generated by Django 4.2.7 on 2025-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_list', 'در لیست انتظار'), ('pending_admin', 'در انتظار تایید ادمین'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='pending_admin', max_length=20),
        ),
    ]
